[build]
  base = "backend/"
  command = "pip install -r requirements.txt"
  functions = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200