[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel"]

[phases.install]
cmds = [
    "python3.11 -m pip install --upgrade pip setuptools wheel",
    "python3.11 -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "echo 'Build completed'",
    "ls -la backend/",
    "echo 'Checking for relat_orgaos.csv:'",
    "ls -la backend/relat_orgaos.csv || echo 'File not found'"
]

[start]
cmd = "cd backend && python3.11 start_server.py"