# Configuração Nixpacks para Railway
[phases.build]
# Primeiro instalar dependências Python
cmds = [
    "pip install -r requirements.txt"
]

[phases.setup]
# Depois construir o React
cmds = [
    "cd frontend && npm install",
    "cd frontend && npm run build", 
    "cp -r frontend/build ."
]

[start]
cmd = "python server.py"