# Configuração Nixpacks para Railway
[phases.setup]
# Instalar Node.js e Python
nixPkgs = ["nodejs_18", "python3", "gcc"]

# Construir React primeiro
cmds = [
    "ls -la",
    "pwd", 
    "cd frontend",
    "npm install",
    "npm run build",
    "cd ..",
    "cp -r frontend/build ."
]

[phases.install]
# Instalar dependências Python
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = "python server.py"