[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && python start_server.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10