name: Deploy Q-FAZ Backend + Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout do repositório
      - uses: actions/checkout@v4

      # 2️⃣ Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3️⃣ Build do frontend React
      - name: Build frontend
        run: |
          cd backend/frontend
          npm install --legacy-peer-deps
          npm run build

      # 4️⃣ Instalar dependências do backend
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      # 5️⃣ Validar secrets do Azure
      - name: Validate required GitHub Secrets
        shell: bash
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          missing=false
          for var in AZURE_CREDENTIALS AZURE_WEBAPP_NAME AZURE_RESOURCE_GROUP MONGO_URL DB_NAME; do
            if [ -z "${!var}" ]; then
              echo "ERROR: $var is not set"
              missing=true
            fi
          done
          if [ "$missing" = true ]; then exit 1; fi

      # 6️⃣ Login no Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 7️⃣ Configurar variáveis de ambiente no Web App
      - name: Configure Azure Web App environment variables
        env:
          AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          az webapp config appsettings set \
            --name $AZURE_WEBAPP_NAME \
            --resource-group $AZURE_RESOURCE_GROUP \
            --settings MONGO_URL=$MONGO_URL DB_NAME=$DB_NAME

      # 8️⃣ Deploy completo do backend + frontend via Node.js
      - name: Deploy backend with frontend
        env:
          AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
        run: |
          cd backend
          zip -r ../backend_deploy.zip . -x "__pycache__/*" "*.pyc"
          cd ..
          az webapp deploy --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_WEBAPP_NAME --src-path backend_deploy.zip
