name: Deploy Backend to Azure Web App

on:
  push:
    branches:
      - main  # ou o branch que você usa

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd backend  # ajuste se sua pasta for diferente
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip project for deployment
        run: |
          cd backend
          zip -r ../deploy.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: qfaz-backend            # nome exato do seu App Service no Azure
          slot-name: Production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deploy.zip
